current_dir = Dir.pwd
Dir["#{current_dir}/models/*.rb"].each { |file| require file }

get '/cars' do
    ...
    @cars = Cars.all
    ...
end

get '/cars/:id' do
    ...
    @car = Car.find(params[:id])
    ...
end

post '/cars' do
    ...
    @car = Car.create(params[:car])
    ...
end

update '/cars/:id' do
    ...
    @car = Car.update(params[:car])
    ...
end

delete '/cars/:id' do
    ...
    Car.destroy(params[:id])
    ...